create table if not exists apps (
  id bigint generated by default as identity primary key,
  name text unique not null,
  developer text,
  category text,
  platform text,
  description text,
  app_url text,
  icon_url text,
  screenshot_urls jsonb default '[]'::jsonb,
  rating numeric,
  review_count integer default 0,
  price numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists app_metrics (
  id bigint generated by default as identity primary key,
  app_id bigint references apps(id) on delete cascade,
  metric_date date not null default current_date,
  rank integer,
  downloads numeric,
  revenue_estimate numeric,
  rating numeric,
  review_count integer,
  growth_rate numeric,
  created_at timestamptz default now(),
  unique(app_id, metric_date)
);

create table if not exists app_analysis (
  id bigint generated by default as identity primary key,
  app_id bigint references apps(id) on delete cascade,
  opportunity_score numeric,
  growth_signal numeric,
  market_signal numeric,
  revenue_signal numeric,
  review_signal numeric,
  ranking_signal numeric,
  target_user text,
  core_features jsonb default '[]'::jsonb,
  monetization text,
  user_pain_points jsonb default '[]'::jsonb,
  market_opportunity text,
  build_opportunity text,
  mvp_features jsonb default '[]'::jsonb,
  risks jsonb default '[]'::jsonb,
  ai_summary text,
  created_at timestamptz default now()
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  report_date date not null default current_date,
  apps_analyzed integer default 0,
  top_opportunities jsonb default '[]'::jsonb,
  html_content text,
  status text default 'generated',
  sent_at timestamptz,
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table apps enable row level security;
alter table app_metrics enable row level security;
alter table app_analysis enable row level security;
alter table reports enable row level security;

-- Policies for public reading (anon / authenticated)
create policy "Allow public read on apps" on apps for select using (true);
create policy "Allow public read on app_metrics" on app_metrics for select using (true);
create policy "Allow public read on app_analysis" on app_analysis for select using (true);
create policy "Allow public read on reports" on reports for select using (true);

-- Policies for ingestion & pipeline writing (anon key)
create policy "Allow public insert on apps" on apps for insert with check (true);
create policy "Allow public update on apps" on apps for update using (true) with check (true);

create policy "Allow public insert on app_metrics" on app_metrics for insert with check (true);
create policy "Allow public update on app_metrics" on app_metrics for update using (true) with check (true);

create policy "Allow public insert on app_analysis" on app_analysis for insert with check (true);
create policy "Allow public update on app_analysis" on app_analysis for update using (true) with check (true);

create policy "Allow public insert on reports" on reports for insert with check (true);
create policy "Allow public update on reports" on reports for update using (true) with check (true);

-- User Watchlists & Personal Opportunity Tracking
create table if not exists user_watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  app_id bigint references apps(id) on delete cascade not null,
  notes text default '',
  created_at timestamptz default now(),
  unique(user_id, app_id)
);

alter table user_watchlists enable row level security;

-- Individual Users can only view, insert, update, delete their own watchlist items
create policy "Users can view own watchlist" on user_watchlists
  for select using (auth.uid() = user_id);

create policy "Users can insert own watchlist" on user_watchlists
  for insert with check (auth.uid() = user_id);

create policy "Users can update own watchlist" on user_watchlists
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can delete own watchlist" on user_watchlists
  for delete using (auth.uid() = user_id);

-- User Subscriptions & Stripe Billing Sync
create table if not exists user_subscriptions (
  user_id uuid references auth.users(id) on delete cascade primary key,
  tier text not null default 'free' check (tier in ('free', 'pro', 'agency')),
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_price_id text,
  status text not null default 'active',
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_subscriptions_stripe_customer 
  on user_subscriptions(stripe_customer_id);

create index if not exists idx_user_subscriptions_stripe_sub 
  on user_subscriptions(stripe_subscription_id);

alter table user_subscriptions enable row level security;

create policy "Users can view own subscription" on user_subscriptions
  for select using (auth.uid() = user_id);

create policy "Users can insert own subscription" on user_subscriptions
  for insert with check (auth.uid() = user_id);

create policy "Users can update own subscription" on user_subscriptions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

