create table if not exists apps (
  id bigint generated by default as identity primary key,
  name text unique not null,
  developer text,
  category text,
  platform text,
  description text,
  app_url text,
  icon_url text,
  screenshot_urls jsonb default '[]'::jsonb,
  rating numeric,
  review_count integer default 0,
  price numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists app_metrics (
  id bigint generated by default as identity primary key,
  app_id bigint references apps(id) on delete cascade,
  metric_date date not null default current_date,
  rank integer,
  downloads numeric,
  revenue_estimate numeric,
  rating numeric,
  review_count integer,
  growth_rate numeric,
  created_at timestamptz default now(),
  unique(app_id, metric_date)
);

create table if not exists app_analysis (
  id bigint generated by default as identity primary key,
  app_id bigint references apps(id) on delete cascade,
  opportunity_score numeric,
  growth_signal numeric,
  market_signal numeric,
  revenue_signal numeric,
  review_signal numeric,
  ranking_signal numeric,
  target_user text,
  core_features jsonb default '[]'::jsonb,
  monetization text,
  user_pain_points jsonb default '[]'::jsonb,
  market_opportunity text,
  build_opportunity text,
  mvp_features jsonb default '[]'::jsonb,
  risks jsonb default '[]'::jsonb,
  ai_summary text,
  created_at timestamptz default now()
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  report_date date not null default current_date,
  apps_analyzed integer default 0,
  top_opportunities jsonb default '[]'::jsonb,
  html_content text,
  status text default 'generated',
  sent_at timestamptz,
  created_at timestamptz default now()
);
