import 'dart:convert';
import '../../data/models/app_item.dart';
import '../../data/models/build_blueprint.dart';
import 'download_helper.dart';

class FileExportService {
  const FileExportService();

  static String _slugify(String name) {
    return name
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
        .replaceAll(RegExp(r'^_+|_+$'), '');
  }

  /// Generates a comprehensive, execution-ready system prompt for AI Coding Agents:
  /// Cursor, Claude Code, Google Antigravity, Gemini CLI, Windsurf.
  String generateCursorPrompt(BuildBlueprint blueprint) {
    final buffer = StringBuffer();

    buffer.writeln('# 🚀 System Specification & Agent Prompt: ${blueprint.appName}');
    buffer.writeln('> Generated by AppRadar SaaS Intelligence Engine');
    buffer.writeln('> Designed for: Cursor IDE / Claude 3.7 Sonnet / Google Antigravity / Windsurf');
    buffer.writeln();
    buffer.writeln('## 🎯 1. Mission & Overview');
    buffer.writeln(blueprint.productOverview);
    buffer.writeln();
    buffer.writeln('## 🛑 2. Problem Statement');
    buffer.writeln(blueprint.problem);
    buffer.writeln();
    buffer.writeln('## 👥 3. Target User & Persona');
    buffer.writeln(blueprint.targetUsers);
    buffer.writeln();
    buffer.writeln('## 💡 4. Core Value Proposition');
    buffer.writeln(blueprint.valueProposition);
    buffer.writeln();
    buffer.writeln('## ⚡ 5. Core MVP Features (Phase 1 Scope)');
    for (final feat in blueprint.coreMvpFeatures) {
      buffer.writeln('- [ ] **$feat**');
    }
    buffer.writeln();
    buffer.writeln('## 🔄 6. User Journey & Navigation Flow');
    for (int i = 0; i < blueprint.userFlow.length; i++) {
      buffer.writeln('${i + 1}. ${blueprint.userFlow[i]}');
    }
    buffer.writeln();
    buffer.writeln('## 📱 7. UI Screen Hierarchy');
    for (final screen in blueprint.screens) {
      buffer.writeln('- **$screen**');
    }
    buffer.writeln();
    buffer.writeln('## 🗄️ 8. Database Architecture (PostgreSQL / Supabase DDL)');
    buffer.writeln('```sql');
    buffer.writeln(blueprint.databaseDesign);
    buffer.writeln('```');
    buffer.writeln();
    buffer.writeln('## 🔌 9. API Requirements & Backend Contracts');
    for (final api in blueprint.apiRequirements) {
      buffer.writeln('- `$api`');
    }
    buffer.writeln();
    buffer.writeln('## 🧠 10. AI Architecture & Prompt Pipelines');
    buffer.writeln(blueprint.aiArchitecture);
    buffer.writeln();
    buffer.writeln('## 🏗️ 11. Flutter Mobile & Web Architecture');
    buffer.writeln(blueprint.flutterArchitecture);
    buffer.writeln();
    buffer.writeln('## 💳 12. Monetization & Stripe Setup');
    buffer.writeln(blueprint.monetization);
    buffer.writeln();
    buffer.writeln('## 🛡️ 13. Competitive Moats & Differentiation');
    for (final diff in blueprint.competitiveDifferentiation) {
      buffer.writeln('- 🌟 $diff');
    }
    buffer.writeln();
    buffer.writeln('## 🗓️ 14. Phased Engineering Roadmap');
    for (final phase in blueprint.roadmap) {
      buffer.writeln('### Phase: ${phase.phase} (${phase.duration})');
      for (final milestone in phase.milestones) {
        buffer.writeln('  - $milestone');
      }
      buffer.writeln();
    }
    buffer.writeln('## 🤖 15. Execution Directives for Coding Agent');
    buffer.writeln('1. Initialize the project with the specified Flutter/Supabase architecture.');
    buffer.writeln('2. Create models, repositories, and state management matching Section 8 & 11.');
    buffer.writeln('3. Implement UI screens following Section 6 & 7 with modern, high-converting aesthetic.');
    buffer.writeln('4. Implement and verify unit and widget tests for all core flows.');
    buffer.writeln('5. Ensure 0 analyzer errors before completing any task.');

    return buffer.toString();
  }

  /// Generates a machine-readable JSON representation of the entire blueprint.
  String generateBlueprintJson(BuildBlueprint blueprint) {
    final map = {
      'appName': blueprint.appName,
      'productOverview': blueprint.productOverview,
      'problem': blueprint.problem,
      'targetUsers': blueprint.targetUsers,
      'valueProposition': blueprint.valueProposition,
      'coreMvpFeatures': blueprint.coreMvpFeatures,
      'userFlow': blueprint.userFlow,
      'screens': blueprint.screens,
      'databaseDesign': blueprint.databaseDesign,
      'apiRequirements': blueprint.apiRequirements,
      'aiArchitecture': blueprint.aiArchitecture,
      'flutterArchitecture': blueprint.flutterArchitecture,
      'monetization': blueprint.monetization,
      'competitiveDifferentiation': blueprint.competitiveDifferentiation,
      'roadmap': blueprint.roadmap.map((r) => {
        'phase': r.phase,
        'duration': r.duration,
        'milestones': r.milestones,
      }).toList(),
      'metadata': {
        'exportedAt': DateTime.now().toUtc().toIso8601String(),
        'engine': 'AppRadar SaaS v1.0',
      }
    };

    return const JsonEncoder.withIndent('  ').convert(map);
  }

  /// Generates CSV report of an app teardown.
  String generateTeardownCsv(AppItem app) {
    final buffer = StringBuffer();
    // Headers
    buffer.writeln('App ID,App Name,Category,Platform,Rating,Review Count,Downloads Estimate,Revenue Estimate,Growth Rate %,Opportunity Score,Composite Signal,Monetization,Dissatisfaction Rate %,Golden Opportunity,Pain Points,Competitor Gaps');

    // Escape values
    String escape(dynamic val) {
      final str = val?.toString() ?? '';
      if (str.contains(',') || str.contains('"') || str.contains('\n')) {
        return '"${str.replaceAll('"', '""')}"';
      }
      return str;
    }

    buffer.writeln([
      escape(app.id),
      escape(app.name),
      escape(app.category),
      escape(app.platform),
      escape(app.rating),
      escape(app.reviewCount),
      escape(app.downloadsEstimate),
      escape(app.revenueEstimate),
      escape(app.growthRate),
      escape(app.opportunityScore),
      escape(app.signals.compositeScore),
      escape(app.monetization),
      escape(app.negativeReviews != null ? '${app.negativeReviews!.dissatisfactionRate}%' : 'N/A'),
      escape(app.negativeReviews?.goldenOpportunitySummary ?? 'N/A'),
      escape(app.userPainPoints.join('; ')),
      escape(app.competitorGaps.join('; ')),
    ].join(','));

    return buffer.toString();
  }

  /// Generates an executive Markdown report of an app teardown.
  String generateTeardownMarkdown(AppItem app) {
    final buffer = StringBuffer();
    buffer.writeln('# Teardown Report: ${app.name} (${app.platform})');
    buffer.writeln('**Developer:** ${app.developer} | **Category:** ${app.category}');
    buffer.writeln('**Rating:** ${app.rating} ⭐ (${app.reviewCount.toString()} reviews)');
    buffer.writeln('**Est. Revenue:** \$${app.revenueEstimate.toStringAsFixed(0)}/mo | **Growth:** +${app.growthRate}%');
    buffer.writeln('**Opportunity Score:** ${app.opportunityScore}/100');
    buffer.writeln();
    buffer.writeln('## What It Does');
    buffer.writeln(app.whatItDoes);
    buffer.writeln();
    buffer.writeln('## Why It is Growing');
    buffer.writeln(app.whyGrowing);
    buffer.writeln();
    buffer.writeln('## User Pain Points & Negative Sentiments');
    for (final p in app.userPainPoints) {
      buffer.writeln('- ⚠️ $p');
    }
    buffer.writeln();
    buffer.writeln('## Competitor Gaps (Where you can win)');
    for (final g in app.competitorGaps) {
      buffer.writeln('- 🎯 $g');
    }
    buffer.writeln();
    buffer.writeln('## Suggested MVP');
    for (final m in app.suggestedMvp) {
      buffer.writeln('- [ ] $m');
    }

    if (app.negativeReviews != null) {
      final mining = app.negativeReviews!;
      buffer.writeln();
      buffer.writeln('## 1★ & 2★ Negative Review Intelligence & User Dissatisfaction');
      buffer.writeln('- **Dissatisfaction Rate:** ${mining.dissatisfactionRate}% (${mining.totalAnalyzed} reviews analyzed)');
      buffer.writeln('- **The Golden Opportunity (How to Win Their Users):** ${mining.goldenOpportunitySummary}');
      buffer.writeln();
      buffer.writeln('### Core Complaint Categories:');
      for (final entry in mining.categoryDistribution.entries) {
        buffer.writeln('- **${entry.key}:** ${entry.value}%');
      }
      buffer.writeln();
      buffer.writeln('### Sample Dissatisfied User Quotes:');
      for (final r in mining.sampleReviews) {
        buffer.writeln('> "${r.comment}" — *${r.author} (${r.rating}★, ${r.category})*');
        buffer.writeln('> **Builder Takeaway:** ${r.builderOpportunity}');
        buffer.writeln();
      }
    }

    return buffer.toString();
  }

  /// Downloads `[AppName]_PROMPT.md` directly via browser download manager.
  void downloadPromptMarkdown(BuildBlueprint blueprint) {
    final fileName = '${_slugify(blueprint.appName)}_PROMPT.md';
    final content = generateCursorPrompt(blueprint);
    downloadFile(fileName: fileName, content: content, mimeType: 'text/markdown;charset=utf-8');
  }

  /// Downloads structured blueprint as JSON.
  void downloadBlueprintJson(BuildBlueprint blueprint) {
    final fileName = '${_slugify(blueprint.appName)}_BLUEPRINT.json';
    final content = generateBlueprintJson(blueprint);
    downloadFile(fileName: fileName, content: content, mimeType: 'application/json;charset=utf-8');
  }

  /// Downloads Teardown data as CSV.
  void downloadTeardownCsv(AppItem app) {
    final fileName = '${_slugify(app.name)}_TEARDOWN.csv';
    final content = generateTeardownCsv(app);
    downloadFile(fileName: fileName, content: content, mimeType: 'text/csv;charset=utf-8');
  }

  /// Downloads Teardown summary as Markdown.
  void downloadTeardownMarkdown(AppItem app) {
    final fileName = '${_slugify(app.name)}_TEARDOWN.md';
    final content = generateTeardownMarkdown(app);
    downloadFile(fileName: fileName, content: content, mimeType: 'text/markdown;charset=utf-8');
  }
}
